config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  resources :cars, only: [ :index, :show ] do
    resources :reviews, only: :create
    resources :favourites, only: :create
  end
  resources :owners, only: :nickname
  resources :favourites, only: :index
  # get 'favourites', to: 'favourite#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner
  has_many :reviews
  has_many :favorites

  validates :brand, :model, :year, :fuel, presence: true
  validates :year, numericality: { only_integer: true }
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :car
  validates :Favourite, presence: true
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :cars
  validates :nickname, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  validates :comment, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @car = car.find(params[:car_id])
    @review = review.new(review_params)
    @review.car = @car
    # @review.car_id = @car.id
    if @review.save
      redirect_to car_path(@car)
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cars/index.html.erb
<h1>Here are the cars!</h1>
<% @cars.each do |car| %>
  <h2><%= car.brand %></h2>
  <h3><%= car.model %></h3>
  <p><%= car.created_at.strftime("%a %b %e at %l%M %p") %></p>
  <div><%= car.owner.nickname %></div>
<% end %>

app/views/cars/show.html.erb
<h2><%= @car.brand %></h2>
<h3><%= @car.model %></h3>
<p><%= @car.fuel %></p>
<p><%= @car.year %></p>

<div class="review-form">
  <%= simple_form_for [@car, @review] do |f| %>
    <%= f.input :comment, label: false, placeholder: "Comment here!", class: "comment-box" %>
    <%= f.input :rating, collection: 0..5, label: false %>
    <%= f.submit 'Add review', class: "add-review-btn" %>
  <% end %>
</div>

<div class="reviews">
  <% @car.reviews.each do |review| %>
    <p><%= review.comment %></p>
    <p>
      <% review.rating.times do %>
        <i class="fa fa-star"></i>
      <% end %>
    </p>
  <% end %>
</div>

<% if @car.favourite.empty? %>
  <div class="save-to-garage">
    <%= simple_form_for [@car, @favourite] do |f| %>
      <%= f.submit 'Save to my garage', class: "save-to-garage-btn" %>
    <% end %>
  </div>
<% else %>
  <p>This car is in your garage</p>
<% end %>

app/views/favorites/index.html.erb
<%= @favourites.each do |favourite| %>
  <p><%= favourite.car.brand %></p>
  <p><%= favourite.car.model %></p>
  <%= link_to "Unfavourite", favourite_path(favourite), data: {turbo_meth} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Awesome Garage" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>